service: lambda-git-layer
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    name: lambda-layer-git-hello
    handler: bin/hello
    layers:
      - !Ref GitLambdaLayer

layers:
  git:
    name: lambda-layer-git
    compatibleRuntimes:
      - go1.x
    compatibleArchitectures:
      - x86_64
    package:
      artifact: ./layer/git.zip
